version: '3'

services:
  postgresdb:
    build: ./postgresql-node
    ports:
      - 5432:5432
  
  netcoreapi:
    build: ./netcoreapi-node
    ports:
      - 8081:80

  nodejsrestapi:
    build: ./nodejs-node
    #volumes:
    #  - ./nodejs-node:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - postgresdb

  angularwebsite:
    build: ./angularjs-node
    #volumes:
    #  - ./angularjs-node/dist/angularjs-node:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - netcoreapi
      - nodejsrestapi