version: '3'

networks:
  backendnet:
    driver: bridge
  frontendnet:
    driver: bridge

services:
  postgresdb:
    build: ./postgresql-node
    networks:
      - backendnet
    ports:
      - 5432:5432
  
  netcoreapi:
    build: ./netcoreapi-node
    networks:
      - backendnet
    ports:
      - 8081:80

  nodejsrestapi:
    build: ./nodejs-node
    networks:
      - backendnet
    ports:
      - 8080:8080
    depends_on:
      - postgresdb

  mongodb:
    image: mongo
    networks:
      - backendnet
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./mongo-seed-populate
    networks:
      - backendnet
    links:
      - mongodb

  angularwebsite:
    build: ./angularjs-node
    networks:
      - frontendnet
    ports:
      - 80:80
